name: 'Build images'
description: 'Build images and push to ACR'
inputs:
  azure-credentials:
    description: 'Azure credentials to sign in'
    required: true
  keystore-password:
    description: 'Key store password'
    required: true
  acr-name:
    description: 'ACR name'
    required: true
  image-tag:
    description: 'Image tag'
    required: true
  nginx-version:
    description: 'Nginx version'
    required: true
  otel-module-version:
    description: 'OpenTelemetry module version'
    required: true
runs:
  using: "composite"
  steps:
    - uses: azure/login@v1
      id: azure-login
      with:
        creds: ${{ inputs.azure-credentials }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: microsoft
        java-version: 17
        cache: 'maven'
    - run: |
        # Build projects, containerize applications and push images to acr
        ${{ github.action_path }}/../../../build.sh ${{ inputs.keystore-password }} ${{ inputs.acr-name }} ${{ inputs.image-tag }} ${{ inputs.nginx-version }} ${{ inputs.otel-module-version }}
      shell: bash
