name: 'Rolling update'
description: 'Rolling update the application in AKS cluster'
inputs:
  azure-credentials:
    description: 'Azure credentials to sign in'
    required: true
  resource-group-name:
    description: 'Resource group where the infrastructure is deployed'
    required: true
  aks-cluster-name:
    description: 'AKS cluster name'
    required: true
  acr-name:
    description: 'ACR name'
    required: true
  image-tag:
    description: 'Image tag'
    required: true
  keystore-password:
    description: 'Key store password'
    required: true
  namespace-name:
    description: 'Namespace name'
    required: true
  nginx-version:
    description: 'Nginx version'
    required: true
  otel-module-version:
    description: 'OpenTelemetry module version'
    required: true
runs:
  using: "composite"
  steps:
    - uses: azure/login@v1
      id: azure-login
      with:
        creds: ${{ inputs.azure-credentials }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: microsoft
        java-version: 17
        cache: 'maven'
    - name: Update application images and perform rolling update
      run: |
        # Rolling update the application
        ${{ github.action_path }}/../../../update.sh ${{ inputs.resource-group-name }} ${{ inputs.aks-cluster-name }} ${{ inputs.acr-name }} \
          ${{ inputs.image-tag }} ${{ inputs.keystore-password }} ${{ inputs.namespace-name }} ${{ inputs.nginx-version }} ${{ inputs.otel-module-version }}
      shell: bash
