name: 'Build image nginx-otel'
on:
  workflow_dispatch:
env:
  nginxVersion: ${{ vars.NGINX_VERSION }}
  otelModuleVersion: ${{ vars.OTEL_MODULE_VERSION }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build image for NGINX with OpenTelemetry module
        uses: ./.github/actions/build-image-nginx-otel
        with:
          ghcr-username: ${{ github.actor }}
          ghcr-password: ${{ secrets.GITHUB_TOKEN }}
          nginx-version: ${{ env.nginxVersion }}
          otel-module-version: ${{ env.otelModuleVersion }}
